<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <AssemblyName>NetworkSpeaker</AssemblyName>
    <RootNamespace>NetworkSpeaker.Launcher</RootNamespace>
    <ApplicationIcon>Resources\app.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Resource Include="Resources\app.ico" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\NetworkSpeaker.Launcher.Core\NetworkSpeaker.Launcher.Core.csproj" />
  </ItemGroup>
</Project>
